### ISSUE TITLE
Gust Book Application links are broken

### ISSUE THREAD

**Issue by MushiTheMoshi** [gitopsbook/resources#22]
Hi there, over the course of the book I tried to do examples in the Chapter 2 and it seems that the runbook application url are broken.

Regards,
Julio

**Comment by billyy** [comment]
Can you tell me the page number or the url you are referring to?  thanks.

**Comment by MushiTheMoshi** [comment]
Hi there, forgot it. Page 61, guest book application I just found them here:
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples.git

**Comment by billyy** [comment]
They moved the location.

**Comment by julioOlea** [comment]
Yeah, I noticed in the next chapter , sorry for the bother.
